title: ConningTower
description: ConningTower Official Site
theme: just-the-docs

url: https://conntower.github.io/docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
